<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\HarborTorrent.Application\HarborTorrent.Application.csproj" />
    <ProjectReference Include="..\HarborTorrent.Domain\HarborTorrent.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MonoTorrent" Version="3.0.2" />
    <PackageReference Include="System.ServiceModel.Syndication" Version="8.0.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>HarborTorrent.Infrastructure</AssemblyName>
    <RootNamespace>HarborTorrent.Infrastructure</RootNamespace>
  </PropertyGroup>

</Project>
