// <auto-generated />
using System;
using HarborTorrent.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HarborTorrent.Persistence.Migrations
{
    [DbContext(typeof(HarborDbContext))]
    [Migration("20260822183818_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("HarborTorrent.Domain.Torrents.Torrent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("AddedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("DownloadSpeedBytesPerSecond")
                        .HasColumnType("INTEGER");

                    b.Property<long>("DownloadedBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<long?>("EtaSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InfoHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Progress")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Ratio")
                        .HasPrecision(8, 3)
                        .HasColumnType("TEXT");

                    b.Property<string>("SavePath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("UploadSpeedBytesPerSecond")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UploadedBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InfoHash")
                        .IsUnique()
                        .HasFilter("\"InfoHash\" <> ''");

                    b.ToTable("Torrents");
                });

            modelBuilder.Entity("HarborTorrent.Domain.Torrents.Torrent", b =>
                {
                    b.OwnsOne("HarborTorrent.Domain.Torrents.TorrentSource", "Source", b1 =>
                        {
                            b1.Property<Guid>("TorrentId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("FileName")
                                .HasMaxLength(256)
                                .HasColumnType("TEXT")
                                .HasColumnName("SourceFileName");

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("TEXT")
                                .HasColumnName("SourceKind");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("SourceValue");

                            b1.HasKey("TorrentId");

                            b1.ToTable("Torrents");

                            b1.WithOwner()
                                .HasForeignKey("TorrentId");
                        });

                    b.Navigation("Source")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
