// <auto-generated />
using System;
using HarborTorrent.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HarborTorrent.Persistence.Migrations
{
    [DbContext(typeof(HarborDbContext))]
    partial class HarborDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("HarborTorrent.Domain.Rss.RssFeed", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastPolledAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RssFeeds");
                });

            modelBuilder.Entity("HarborTorrent.Domain.Rss.RssFeedItemHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemIdentifier")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RssFeedId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RssFilterId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RssFeedId", "ItemIdentifier")
                        .IsUnique();

                    b.ToTable("RssFeedItemHistories");
                });

            modelBuilder.Entity("HarborTorrent.Domain.Rss.RssFilter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("RegexPattern")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RssFeedId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SavePath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RssFeedId");

                    b.ToTable("RssFilters");
                });

            modelBuilder.Entity("HarborTorrent.Domain.Settings.GlobalSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AnchorMaxDownloadSpeedBytes")
                        .HasColumnType("INTEGER");

                    b.Property<long>("AnchorMaxUploadSpeedBytes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AnchorModeEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DefaultDownloadPath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EnableDht")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableLpd")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnablePex")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MaxDownloadSpeedBytes")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MaxUploadSpeedBytes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("HarborTorrent.Domain.Torrents.Torrent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("AddedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("DownloadSpeedBytesPerSecond")
                        .HasColumnType("INTEGER");

                    b.Property<long>("DownloadedBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<long?>("EtaSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InfoHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Progress")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Ratio")
                        .HasPrecision(8, 3)
                        .HasColumnType("TEXT");

                    b.Property<string>("SavePath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("UploadSpeedBytesPerSecond")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UploadedBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InfoHash")
                        .IsUnique()
                        .HasFilter("\"InfoHash\" <> ''");

                    b.ToTable("Torrents");
                });

            modelBuilder.Entity("HarborTorrent.Domain.Rss.RssFilter", b =>
                {
                    b.HasOne("HarborTorrent.Domain.Rss.RssFeed", null)
                        .WithMany("Filters")
                        .HasForeignKey("RssFeedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HarborTorrent.Domain.Torrents.Torrent", b =>
                {
                    b.OwnsOne("HarborTorrent.Domain.Torrents.TorrentSource", "Source", b1 =>
                        {
                            b1.Property<Guid>("TorrentId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("FileName")
                                .HasMaxLength(256)
                                .HasColumnType("TEXT")
                                .HasColumnName("SourceFileName");

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("TEXT")
                                .HasColumnName("SourceKind");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("SourceValue");

                            b1.HasKey("TorrentId");

                            b1.ToTable("Torrents");

                            b1.WithOwner()
                                .HasForeignKey("TorrentId");
                        });

                    b.Navigation("Source")
                        .IsRequired();
                });

            modelBuilder.Entity("HarborTorrent.Domain.Rss.RssFeed", b =>
                {
                    b.Navigation("Filters");
                });
#pragma warning restore 612, 618
        }
    }
}
