namespace HarborTorrent.Api.Middleware;

/// <summary>
/// Rejects any request that does not present the per-session launch token.
///
/// Accepted token locations (checked in order):
/// <list type="bullet">
///   <item><c>X-Launch-Token</c> request header — used by the HTTP API client on all routes.</item>
///   <item><c>Authorization: Bearer &lt;token&gt;</c> header — used by the SignalR JS client on
///   hub negotiation and transport requests, because the client's <c>accessTokenFactory</c>
///   injects the token into the Authorization header rather than a custom header.</item>
/// </list>
///
/// The token is generated by the Tauri host at startup and passed to the sidecar via
/// the <c>HARBOR_LAUNCH_TOKEN</c> environment variable. It is valid only for the
/// lifetime of the current process.
/// </summary>
/// <remarks>
/// The <c>/health</c> endpoint is exempt so that the frontend readiness check can
/// poll it before the WebView has retrieved its token via the Tauri invoke bridge.
/// </remarks>
internal sealed class LaunchTokenAuthenticationMiddleware
{
    internal const string HeaderName = "X-Launch-Token";
    private const string BearerPrefix = "Bearer ";

    private static readonly string[] ExemptPaths = ["/health"];

    private readonly RequestDelegate _next;
    private readonly string _expectedToken;

    public LaunchTokenAuthenticationMiddleware(RequestDelegate next, string expectedToken)
    {
        _next = next;
        _expectedToken = expectedToken;
    }

    public async Task InvokeAsync(HttpContext context)
    {
        if (IsExempt(context.Request.Path))
        {
            await _next(context);
            return;
        }

        if (IsAuthenticated(context.Request))
        {
            await _next(context);
            return;
        }

        context.Response.StatusCode = StatusCodes.Status401Unauthorized;
        context.Response.ContentType = "application/json";
        await context.Response.WriteAsJsonAsync(new
        {
            success = false,
            errors = new[] { new { code = "unauthorized", message = "Invalid or missing launch token." } }
        });
    }

    private bool IsAuthenticated(HttpRequest request)
    {
        // Check the custom header used by the HTTP API client.
        if (request.Headers.TryGetValue(HeaderName, out var headerValue) &&
            string.Equals(headerValue, _expectedToken, StringComparison.Ordinal))
        {
            return true;
        }

        // Check the Authorization: Bearer header used by the SignalR JS client.
        // The SignalR client's accessTokenFactory places the token here during
        // hub negotiation and WebSocket/SSE upgrade requests.
        if (request.Headers.TryGetValue("Authorization", out var authValue))
        {
            var auth = authValue.ToString();
            if (auth.StartsWith(BearerPrefix, StringComparison.OrdinalIgnoreCase))
            {
                var bearer = auth[BearerPrefix.Length..];
                if (string.Equals(bearer, _expectedToken, StringComparison.Ordinal))
                {
                    return true;
                }
            }
        }

        return false;
    }

    private static bool IsExempt(PathString path)
    {
        foreach (var exemptPath in ExemptPaths)
        {
            if (path.StartsWithSegments(exemptPath, StringComparison.OrdinalIgnoreCase))
            {
                return true;
            }
        }

        return false;
    }
}
