namespace HarborTorrent.Api.Middleware;

/// <summary>
/// Rejects any request that does not present the per-session launch token in the
/// <c>X-Launch-Token</c> request header. The token is generated by the Tauri host
/// at startup and passed to the sidecar via the <c>HARBOR_LAUNCH_TOKEN</c> environment
/// variable. It is valid only for the lifetime of the current process.
/// </summary>
/// <remarks>
/// The <c>/health</c> endpoint is exempt so that the frontend readiness check can
/// poll it before the WebView has retrieved its token via the Tauri invoke bridge.
/// </remarks>
internal sealed class LaunchTokenAuthenticationMiddleware
{
    internal const string HeaderName = "X-Launch-Token";

    private static readonly string[] ExemptPaths = ["/health"];

    private readonly RequestDelegate _next;
    private readonly string _expectedToken;

    public LaunchTokenAuthenticationMiddleware(RequestDelegate next, string expectedToken)
    {
        _next = next;
        _expectedToken = expectedToken;
    }

    public async Task InvokeAsync(HttpContext context)
    {
        if (IsExempt(context.Request.Path))
        {
            await _next(context);
            return;
        }

        if (!context.Request.Headers.TryGetValue(HeaderName, out var value) ||
            !string.Equals(value, _expectedToken, StringComparison.Ordinal))
        {
            context.Response.StatusCode = StatusCodes.Status401Unauthorized;
            context.Response.ContentType = "application/json";
            await context.Response.WriteAsJsonAsync(new
            {
                success = false,
                errors = new[] { new { code = "unauthorized", message = "Invalid or missing launch token." } }
            });
            return;
        }

        await _next(context);
    }

    private static bool IsExempt(PathString path)
    {
        foreach (var exemptPath in ExemptPaths)
        {
            if (path.StartsWithSegments(exemptPath, StringComparison.OrdinalIgnoreCase))
            {
                return true;
            }
        }

        return false;
    }
}
