<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <NoWarn>$(NoWarn);NU1903;NU1603</NoWarn>
    <AssemblyName>HarborTorrent.Api</AssemblyName>
    <RootNamespace>HarborTorrent.Api</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Scalar.AspNetCore" Version="2.16.11" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HarborTorrent.Application\HarborTorrent.Application.csproj" />
    <ProjectReference Include="..\HarborTorrent.Infrastructure\HarborTorrent.Infrastructure.csproj" />
    <ProjectReference Include="..\HarborTorrent.Persistence\HarborTorrent.Persistence.csproj" />
  </ItemGroup>

</Project>
